version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
      - ./minio-init:/docker-entrypoint-init.d

  minio-api:
    build:
      context: .
    container_name: minio-api
    ports:
      - "5000:5000"
    environment:
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_BUCKET_NAME: "test-bucket"
      API_KEY: "my-secure-api-key"
    depends_on:
      - minio

volumes:
  minio-data:
